#cloud-config
users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC547cCbx7VHDJoMmfcZ0XWso7yo6iEEpjYTAa1YoFA4ulF4FgeQkG1iE+0xXNysKsUTxi7atmO0rzCvKaK45uwokDqJmM/0DY5Lh4PknWFSlatPV2lU6qRMwvmhqmKUmfGV+qwf3w4A3kirq7Fhx7+HNab3y2dHqyTQ8W7f6AVd7mvhtV1jM+JVGtRVvtDcfV+0Wdecu4Zn3Hog9F1TBR4EuRCXf/vz+J5xdvhe+M9ol9UaUcgxqw3m8aIEn4obafkClf2OmRoxNIUzjMpeAajBUAEGI9Pqyon7Xv7gURfHvCaWf47UtL2TID1ck/cxEIr2O8yMW/zjqNo8cF0wt2DK7LyFzQ/h4NekkAVvbj/RapqYYxLrChivM5CJXyKGXjBccrKWPUjTDtHTrDZDaLFrqYfQUrKeOrX20N/hqPM38QqSAX5HdV9OIGEoAzdkHfAd3fjA+tT52PBGfCsRl8j9kE08eMKWFJsVnqQInAGHrWDKUaOM5OuU8EWoIR62eE= root@tmv-lab
  - name: maxim
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC547cCbx7VHDJoMmfcZ0XWso7yo6iEEpjYTAa1YoFA4ulF4FgeQkG1iE+0xXNysKsUTxi7atmO0rzCvKaK45uwokDqJmM/0DY5Lh4PknWFSlatPV2lU6qRMwvmhqmKUmfGV+qwf3w4A3kirq7Fhx7+HNab3y2dHqyTQ8W7f6AVd7mvhtV1jM+JVGtRVvtDcfV+0Wdecu4Zn3Hog9F1TBR4EuRCXf/vz+J5xdvhe+M9ol9UaUcgxqw3m8aIEn4obafkClf2OmRoxNIUzjMpeAajBUAEGI9Pqyon7Xv7gURfHvCaWf47UtL2TID1ck/cxEIr2O8yMW/zjqNo8cF0wt2DK7LyFzQ/h4NekkAVvbj/RapqYYxLrChivM5CJXyKGXjBccrKWPUjTDtHTrDZDaLFrqYfQUrKeOrX20N/hqPM38QqSAX5HdV9OIGEoAzdkHfAd3fjA+tT52PBGfCsRl8j9kE08eMKWFJsVnqQInAGHrWDKUaOM5OuU8EWoIR62eE= root@tmv-lab
apt:
  sources:
    mongodb:
      source: "deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse"
      key: |
         -----BEGIN PGP PUBLIC KEY BLOCK-----
         Version: GnuPG v1

         mQINBFrXrqYBEACscLj2qgPpHBCQtgW1Yh29Ddgv6jssyWLAYmj0qngFLKoQMMbt
         SNBZylIKxfS+pUD9J5xfRZwfZOmtMIOFVWS9tcpeQXsiwC126tRyoFCIpoTmH7+R
         8/FfPrCYyXLP+ftEZfRV60wTwr5drR0S5pVIST3oaXXGkHkFC35U++udUG2Tl4Cs
         OPSCp1tsK6UOTjHFDH8PnasImJgD37QC8OOMIJS0jCtDZywJW6OCdpIRbuTWPK3P
         P48NLwGUJHixhVCmOgPPu9kDAfG3wLxiN85S2UbaaSXsdA4fF4SSwWNHTIYAg0yT
         xGepVyW4lkfcvng4jva24rQ9j1cm1b7bWeOkMH1aAcSyFzKCeNCNxbVOYVrcWNP4
         zrSUvsTKhwX8rPFMq9LkcKirDL9bRILvn/24VU6NdJfGbRjR6+Q7ooj7hYKLXtO5
         q0Q4nhjigpTWIoU6jdfbM9YqpKSELNnkDRAU+bRYSrNaFuizYgDZQvcVT6gbq26f
         JbgihoeJogEfim3kqRRJ3EUhE+EaVijl9iLDKkpurod26P2QSq9RKSuOCeauPjQv
         3BIiEMXco8O3v8W1y4TbnSQ3d28W9pN28IgAhmN2EU2sKqWPzNeG0V+L6mE5pA4o
         nD3z3JRpxAUFw08+9LnLRZ4D1u54OrHADsU8UpYZJCm1xw6T0e4dlxW6rQARAQAB
         tDdNb25nb0RCIDQuMiBSZWxlYXNlIFNpZ25pbmcgS2V5IDxwYWNrYWdpbmdAbW9u
         Z29kYi5jb20+iQI+BBMBAgAoAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAUC
         ZD22HAUJDShucAAKCRBLfFSaBY+La6Z+D/9Bbh4DCvmgJk8BQ1icX8w4AyDpEjoj
         XasL9A+IK+wTsphIn89QSx5whWN/zhqIswZPj5M5PdGC/fi8sF19XEmXRmiprAMC
         z6MoejpjHwCxrcb76xnxyGAH/TqtS7BjbR8qM2ksmlmJAEB99RtJBHseOyi95O9+
         smIctlVjJvHmmF4XPv+EiCOq4eRaDG0sKXpw5Kpqy78IU2Vs3d5qzJTmdIVfsenD
         eRAerJ2zE8NYSS8+rtmr42p/yh2SpKyERS1wq91ZbEYLAKdRZXaOxGEY5aVmY0WS
         0jTRgOH8MCkgIfZhxxYPdaTvI60n4MHZASBBBGp3HVZNivuH8ed6Qb/u4hqmG8c0
         kaUeU5TQs6wMSCPsGoFnbS4ysN/9wsFIFEFOsw1a4faG8Wy6+Wc7HSlFNxmKMdLn
         fEpNrIpX7wT2TKEZAOnOFq1bdch5lod5TbfywnpYEIG9m0bmCPrTXLGlqqrGUmpx
         1Y3AWpbtgJxxxQDpGEFTUYKo/GlvCq1QSP2cymmPxsDeZw6l3Famz4g86SCY+SPM
         qRN40TuVd4TBmSDGMQUe+S513ivZvSSPGQ/zVgxi8rF6LMlPyeq7P3ChKSdaCgbU
         fA5RCZpwDOYfndhGDFkWtojp6WgSTtCrR5HLM8ONIgDRGfnXuQc+ka1OP/lwlkRb
         rGMB3Ivdlw9jSA==
         =kjEh
         -----END PGP PUBLIC KEY BLOCK-----
package_update: true
package_upgrade: true
packages:
  - nano
  - mongodb-org
  - git
  - ruby-full
  - ruby-bundler
  - build-essential
runcmd:
  - sudo systemctl start mongod
  - sudo systemctl enable mongod
  - cd /home/yc-user
  - git clone -b monolith "https://github.com/express42/reddit.git"
  - cd reddit && bundle install
  - puma -d
